### ISSUE TITLE
ExpirationReadable is not a field of struct type interface

### ISSUE THREAD

**Issue by vikbez** [espebra/filebin#14]
Building from latest https://github.com/espebra/filebin/commit/2eb6042573b57b29a266fe8c0eddd4366eb7f274 gives me white page on '/' access; and gives the error below.

Building from this commit works: https://github.com/espebra/filebin/commit/297a7f528d2d06d158f8c79db1f0670cbaf720a3

full debug:

```
- 2016/06/22 18:04:25 Generate new bin 43mm302z6qj16v6y
r-49ao0 2016/06/22 18:04:25 Response status: 200
r-49ao0 2016/06/22 18:04:25 template: newbin:71:32: executing "newbin" at <.Data.ExpirationRead...>: ExpirationReadable is not a field of struct type interface {}
2016/06/22 18:04:25 http: panic serving 127.0.0.1:40618: template: newbin:71:32: executing "newbin" at <.Data.ExpirationRead...>: ExpirationReadable is not a field of struct type interface {}

goroutine 8 [running]:
net/http.(*conn).serve.func1(0xc839988000)
    /usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x887ca0, 0xc839937c20)
    /usr/local/go/src/runtime/panic.go:426 +0x4e9
log.(*Logger).Panicln(0xc839984500, 0xc820163140, 0x1, 0x1)
    /usr/local/go/src/log/log.go:220 +0xbf
github.com/espebra/filebin/app/output.HTMLresponse(0x7f183242cf60, 0xc839990090, 0xa1fac8, 0x6, 0xc8, 0x9d9fa0, 0xc83996a280, 0xc8201ce750, 0xc8201ce720, 0x7fff4f0d5dae, ...)
    /home/vik/go/src/github.com/espebra/filebin/app/output/output.go:58 +0xa28
github.com/espebra/filebin/app/api.NewBin(0x7f183242cf60, 0xc839990090, 0xc839992000, 0x7fff4f0d5dd3, 0x9, 0x7a69, 0xe10, 0xe10, 0x100000, 0x7fff4f0d5d6d, ...)
    /home/vik/go/src/github.com/espebra/filebin/app/api/api.go:519 +0x365
main.reqHandler.func1(0x7f183242cf60, 0xc839990090, 0xc839992000)
    /home/vik/go/src/github.com/espebra/filebin/main.go:421 +0xb25
net/http.HandlerFunc.ServeHTTP(0xc83992d0d0, 0x7f183242cf60, 0xc839990090, 0xc839992000)
    /usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc8398cc280, 0x7f183242cf60, 0xc839990090, 0xc839992000)
    /home/vik/go/src/github.com/gorilla/mux/mux.go:107 +0x297
github.com/gorilla/handlers.combinedLoggingHandler.ServeHTTP(0x7f18324211c0, 0xc8200240c0, 0x7f18323a0210, 0xc8398cc280, 0x7f183242cdc0, 0xc839981a00, 0xc839992000)
    /home/vik/go/src/github.com/gorilla/handlers/handlers.go:77 +0x121
github.com/gorilla/handlers.(*combinedLoggingHandler).ServeHTTP(0xc839945860, 0x7f183242cdc0, 0xc839981a00, 0xc839992000)
    <autogenerated>:15 +0xb4
net/http.serverHandler.ServeHTTP(0xc8398c3480, 0x7f183242cdc0, 0xc839981a00, 0xc839992000)
    /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc839988000)
    /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:2137 +0x44e
```

**Comment by espebra** [comment]
Hi,

This is a bit strange. At this point I suspect that a git pull will solve it, since ``templates/newbin.html`` doesn't contain ``.Data.ExpirationReadable`` in the [revision you are referring to](https://github.com/espebra/filebin/blob/2eb6042573b57b29a266fe8c0eddd4366eb7f274/templates/newbin.html#L73) (which is HEAD of master currently). Can you please verify that the repository is correctly cloned at the latest revision?

**Comment by vikbez** [comment]
Well I tried to completely remove the repo and cloned it again, and now it works.
Sorry for the disturbance !
